export const homeObjOne = {
  id: "about",
  lightBg: true,
  lightText: true,
  lightTextDesc: false,
  topLine: "Custom Herbs For Your Health",
  headline: "Hand Crafted Personalized Medicine",
  description:
    "We Craft Our Herbs Straight From Mother Nature! All herbs are harvested sustainably from the wild.",
  buttonLabel: "Learn More",
  imgStart: false,
  img: require("../../images/svg-1.svg"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: false,
};
export const homeObjTwo = {
  id: "discover",
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: "We Go Above And Beyond",
  headline: "First of its kind market for custom powerful herbal medicines",
  description:
    "Get acesdajasldkfjak aghalknlabjlkabljkasadjkladvjklavjl;kdasjl;abjklalabsdkljakslbj",
  buttonLabel: "Learn More",
  imgStart: true,
  img: require("../../images/svg-2.svg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: true,
};
export const homeObjThree = {
  id: "about",
  lightBg: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "Unlimited Transaction With Zero Fees",
  description:
    "Get acesdajasldkfjak aghalknlabjlkabljkasadjkladvjklavjl;kdasjl;abjklalabsdkljakslbj",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/svg-3.svg"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: false,
};
